--DISABLE foreign keys for insertion
ALTER TABLE HEROES DISABLE CONSTRAINT FK_heroes_Partida_game_id;
ALTER TABLE HABILIDADES DISABLE CONSTRAINT FK_habilidades_heroes_hero_id;
ALTER TABLE MAPAS DISABLE CONSTRAINT FK_mapas_partida_game_id;
ALTER TABLE USUARIOS DISABLE CONSTRAINT FK_usuarios_partida_game_id;
ALTER TABLE ARCHIVO_CODIGO DISABLE CONSTRAINT FK_ARCHIVO_CODIGO_habilidades_hability_id;
ALTER TABLE ARCHIVO_CODIGO DISABLE CONSTRAINT FK_ARCHIVO_CODIGO_mapas_map_id;
ALTER TABLE ARCHIVO_CODIGO DISABLE CONSTRAINT FK_ARCHIVO_CODIGO_usuarios_user_id;

INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 30.02, TO_DATE('2017/01/15 10:30:25', 'YYYY/MM/DD HH:MI:SS'),'Free for all');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 45.42, TO_DATE('2018/01/16 4:30:25', 'YYYY/MM/DD HH:MI:SS'),'Conquest');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 30.25, TO_DATE('2018/02/16 10:30:25', 'YYYY/MM/DD HH:MI:SS'),'Disarm');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 40.18, TO_DATE('2019/02/16 9:30:25', 'YYYY/MM/DD HH:MI:SS'),'Battle Royale');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 12.23, TO_DATE('2019/02/16 10:30:25', 'YYYY/MM/DD HH:MI:SS'),'5vs5');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 31.47, TO_DATE('2019/02/16 11:30:25', 'YYYY/MM/DD HH:MI:SS'),'Conquest');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 50.26, TO_DATE('2019/03/16 12:30:25', 'YYYY/MM/DD HH:MI:SS'),'Disarm');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 60.41, TO_DATE('2019/03/16 6:30:25', 'YYYY/MM/DD HH:MI:SS'),'Disarm');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 80.21, TO_DATE('2019/03/17 12:30:25', 'YYYY/MM/DD HH:MI:SS'),'Conquest');
INSERT INTO PARTIDA VALUES (partida_primary_sequence.NEXTVAL, 39.59, TO_DATE('2019/05/17 5:30:25', 'YYYY/MM/DD HH:MI:SS'),'Free for all');

INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Islandia', 'Desert', 1);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Marte', 'Ocean', 2);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Cuba', 'Montain', 3);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Grieta', 'Forest', 4);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Dust_2', 'Urban', 3);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Mercado', 'Sub-Urban', 2);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Assault', 'Favela', 2);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Iran', 'Ocean', 1);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Primavera', 'Conquest', 2);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Japon', 'Urban', 3);
INSERT INTO MAPAS VALUES (mapas_primary_sequence.NEXTVAL, 'Cocina', 'Urban', 4);

INSERT INTO HEROES VALUES (1001, 'Medusa', 'Dire', 1);
INSERT INTO HEROES VALUES (1002, 'Juggernaut', 'Radiant', 1);
INSERT INTO HEROES VALUES (1003, 'Luna', 'Radiant', 2);
INSERT INTO HEROES VALUES (1004, 'Lion', 'Dire', 8);
INSERT INTO HEROES VALUES (1005, 'Shadow Deamon', 'Dire', 3);

INSERT INTO HABILIDADES VALUES (habilidades_primary_sequence.NEXTVAL, 'Stone Gaze', 0, 1001);
INSERT INTO HABILIDADES VALUES (habilidades_primary_sequence.NEXTVAL, 'Mistic Snake', 300, 1001);
INSERT INTO HABILIDADES VALUES (habilidades_primary_sequence.NEXTVAL, 'Battle Fury', 200, 1002);
INSERT INTO HABILIDADES VALUES (habilidades_primary_sequence.NEXTVAL, 'Healing Ward', 0, 1002);
INSERT INTO HABILIDADES VALUES (habilidades_primary_sequence.NEXTVAL, 'Eclipse', 1000, 1003);
INSERT INTO HABILIDADES VALUES (habilidades_primary_sequence.NEXTVAL, 'Death Finger', 1400, 1004);
INSERT INTO HABILIDADES VALUES (habilidades_primary_sequence.NEXTVAL, 'Shadow Raze', 300, 1005);

INSERT INTO USUARIOS VALUES (2001, 'Jack', TO_DATE('2018/05/17 3:29:25', 'YYYY/MM/DD HH:MI:SS'), 1);
INSERT INTO USUARIOS VALUES (2002, 'Marco', TO_DATE('2018/05/17 4:29:25', 'YYYY/MM/DD HH:MI:SS'), 2);
INSERT INTO USUARIOS VALUES (2003, 'Heider', TO_DATE('2018/05/17 5:29:25', 'YYYY/MM/DD HH:MI:SS'), 1);
INSERT INTO USUARIOS VALUES (2004, 'Juan', TO_DATE('2018/05/17 6:29:25', 'YYYY/MM/DD HH:MI:SS'), 3);
INSERT INTO USUARIOS VALUES (2005, 'Killer', TO_DATE('2018/05/17 7:29:25', 'YYYY/MM/DD HH:MI:SS'), 4);

-- KEY, NAME, HABILIDADES, MAPAS, USUARIO
INSERT INTO ARCHIVO_CODIGO VALUES (3001, 'Python', 1, 1, 2001);
INSERT INTO ARCHIVO_CODIGO VALUES (3002, 'C++', 1, 1, 2001);
INSERT INTO ARCHIVO_CODIGO VALUES (3003, 'C', 2, 1, 2003);
INSERT INTO ARCHIVO_CODIGO VALUES (3004, 'Java', 3, 2, 2004);
INSERT INTO ARCHIVO_CODIGO VALUES (3005, 'Javascript', 1, 3, 2005);
INSERT INTO ARCHIVO_CODIGO VALUES (3006, 'Visual Basic', 2, 1, 2001);

--ENABLE foreign keys again
ALTER TABLE HEROES ENABLE CONSTRAINT FK_heroes_Partida_game_id;
ALTER TABLE HABILIDADES ENABLE CONSTRAINT FK_habilidades_heroes_hero_id;
ALTER TABLE MAPAS ENABLE CONSTRAINT FK_mapas_partida_game_id;
ALTER TABLE USUARIOS ENABLE CONSTRAINT FK_usuarios_partida_game_id;
ALTER TABLE ARCHIVO_CODIGO ENABLE CONSTRAINT FK_ARCHIVO_CODIGO_habilidades_hability_id;
ALTER TABLE ARCHIVO_CODIGO ENABLE CONSTRAINT FK_ARCHIVO_CODIGO_mapas_map_id;
ALTER TABLE ARCHIVO_CODIGO ENABLE CONSTRAINT FK_ARCHIVO_CODIGO_usuarios_user_id;