CREATE USER externo07 IDENTIFIED BY a1234;
CREATE ROLE rolExterno07 IDENTIFIED BY a1234; 

GRANT SELECT ON PARTIDA TO rolExterno07;
GRANT SELECT ON MAPAS TO rolExterno07;
GRANT SELECT ON HEROES TO rolExterno07;
GRANT SELECT ON ARCHIVO_CODIGO TO rolExterno07;
GRANT SELECT ON USUARIOS TO rolExterno07;
GRANT SELECT ON HABILIDADES TO rolExterno07;

GRANT DELETE ON ARCHIVO_CODIGO TO rolExterno07;

GRANT UPDATE ON USUARIOS TO rolExterno07;
GRANT UPDATE ON PARTIDA TO rolExterno07;
GRANT UPDATE ON HEROES TO rolExterno07;

GRANT INSERT ON PARTIDA TO rolExterno07;
GRANT INSERT ON HEROES TO rolExterno07;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW TO rolExterno07;

GRANT rolExterno07 to externo07;